import type { Metadata } from "next";
import "@/assets/scss/app.scss";
import AppProviders from "@/providers/AppProviders";
import { LayoutProps } from "@/types/app";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { getMessages } from "next-intl/server";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import MirageProvider from "@/providers/MirageProvider";

config.autoAddCss = false;

export const metadata: Metadata = {
    title: "Omnisell",
    description: "Generated by create next app",
};

interface Props extends LayoutProps {
    params: { locale: string };
}

export default async function RootLayout({ children, params }: Props) {
    const { locale } = await params;
    let messages;
    try {
        messages = await getMessages();
    } catch (error) {
        console.error(error);
        notFound();
    }
    return (
        <html lang={locale}>
            <NextIntlClientProvider locale={locale} messages={messages}>
                <AppProviders>
                    {/* <MirageProvider /> */}
                    <body>{children}</body>
                </AppProviders>
            </NextIntlClientProvider>
        </html>
    );
}
