import type { Metadata } from "next";
import "@/assets/scss/app.scss";
import AppProviders from "@/providers/AppProviders";
import { LayoutProps } from "@/types/app";

export const metadata: Metadata = {
    title: "Omnisell",
    description: "Generated by create next app",
};

interface Props extends LayoutProps {}

export default function RootLayout({ children }: Props) {
    return (
        <html lang="en">
            <AppProviders>
                <body>{children}</body>
            </AppProviders>
        </html>
    );
}
